on: push
name: Remark Lint
jobs:
  remark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Running Remark
        uses: ocular-d/action-remark@0.0.10
        with:
          check_dir: 'md'

      - name: Create Issue
        if: ${{ steps.remark.outputs.exit_code }}
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: Report
          content-filepath: error.log
          labels: report, automated issue

      - name: Fail if there were lint errors
        run: exit ${{ steps.remark.outputs.exit_code }}